apiVersion: v1
kind: Service
metadata:
  name: translate-app-service
spec:
  selector:
    app: translate-app
  ports:
  - protocol: TCP
    name: http
    port: 8000
    targetPort: 8000
  - protocol: TCP
    name: metrics
    port: 8265
    targetPort: 8265
  type: LoadBalancer
